export const CONTRACTORS = [
  {
    id: 'maya',
    name: 'Maya Chen',
    initials: 'MC',
    role: 'Product Designer',
    city: 'Mexico City',
    country: 'Mexico',
    flag: '🇲🇽',
    currency: 'MXN',
    rate: 'MX$840 / hr',
    amount: 4650.00,
    localAmount: '93,560 MXN',
    rail: 'Local rail · SPEI',
    fx: '20.12',
    fee: '$0',
    eta: 'Today, 2 hrs',
    tone: 'sand',
    portrait: false,
    msa: 'MSA 047',
    pinX: 23, pinY: 32,
  },
  {
    id: 'carlos',
    name: 'Carlos Reyes',
    initials: 'CR',
    role: 'Backend Engineer',
    city: 'Buenos Aires',
    country: 'Argentina',
    currency: 'ARS',
    rate: 'AR$ 64,000 / hr',
    amount: 6800.00,
    localAmount: '6.92M ARS',
    rail: 'SWIFT',
    fx: '1018.4',
    fee: '$8.00',
    eta: '2 days',
    tone: 'mist',
    portrait: false,
    msa: 'MSA 042',
    pinX: 34, pinY: 55,
  },
  {
    id: 'amaru',
    name: 'Amaru Quispe',
    initials: 'AQ',
    role: 'Field Researcher',
    city: 'Lima',
    country: 'Peru',
    currency: 'PEN',
    rate: 'S/ 220 / hr',
    amount: 2150.00,
    localAmount: '8,140 PEN',
    rail: 'Local rail',
    fx: '3.79',
    fee: '$2.00',
    eta: 'Tomorrow',
    tone: 'mist',
    portrait: true,
    msa: 'MSA 051',
    pinX: 30, pinY: 50,
  },
  {
    id: 'priya',
    name: 'Priya Iyer',
    initials: 'PI',
    role: 'iOS Engineer',
    city: 'Bengaluru',
    country: 'India',
    currency: 'INR',
    rate: '₹6,400 / hr',
    amount: 5400.00,
    localAmount: '4.51L INR',
    rail: 'Local rail · IMPS',
    fx: '83.5',
    fee: '$0',
    eta: 'Today, 4 hrs',
    tone: 'sand',
    portrait: false,
    msa: 'MSA 049',
    pinX: 71, pinY: 38,
  },
  {
    id: 'nathaniel',
    name: 'Nathaniel Mills',
    initials: 'NM',
    role: 'Brand Strategist',
    city: 'Lisbon',
    country: 'Portugal',
    currency: 'EUR',
    rate: '€110 / hr',
    amount: 3120.00,
    localAmount: '2,890 EUR',
    rail: 'SEPA',
    fx: '0.93',
    fee: '$0',
    eta: 'Today, 6 hrs',
    tone: 'mist',
    portrait: true,
    msa: 'MSA 044',
    pinX: 47, pinY: 25,
  },
  {
    id: 'hallie',
    name: 'Hallie Alvarado',
    initials: 'HA',
    role: 'Content Editor',
    city: 'Madrid',
    country: 'Spain',
    currency: 'EUR',
    rate: '€85 / hr',
    amount: 2280.00,
    localAmount: '2,110 EUR',
    rail: 'SEPA',
    fx: '0.93',
    fee: '$0',
    eta: 'Today, 6 hrs',
    tone: 'mist',
    portrait: false,
    msa: 'MSA 052',
    pinX: 49, pinY: 25,
  },
  {
    id: 'koen',
    name: 'Koen Visser',
    initials: 'KV',
    role: 'Data Engineer',
    city: 'Amsterdam',
    country: 'Netherlands',
    currency: 'EUR',
    rate: '€140 / hr',
    amount: 7320.00,
    localAmount: '6,780 EUR',
    rail: 'SEPA',
    fx: '0.93',
    fee: '$0',
    eta: 'Today, 5 hrs',
    tone: 'mist',
    portrait: false,
    msa: 'MSA 038',
    pinX: 51, pinY: 23,
  },
  {
    id: 'aoife',
    name: 'Aoife Brennan',
    initials: 'AB',
    role: 'Legal Counsel',
    city: 'Dublin',
    country: 'Ireland',
    currency: 'EUR',
    rate: '€180 / hr',
    amount: 4860.00,
    localAmount: '4,500 EUR',
    rail: 'SEPA',
    fx: '0.93',
    fee: '$0',
    eta: 'Today, 6 hrs',
    tone: 'mist',
    portrait: true,
    msa: 'MSA 027',
    pinX: 48, pinY: 23,
  },
  {
    id: 'tomi',
    name: 'Tomi Adebayo',
    initials: 'TA',
    role: 'Growth Analyst',
    city: 'Lagos',
    country: 'Nigeria',
    currency: 'NGN',
    rate: '₦62,000 / hr',
    amount: 1840.00,
    localAmount: '2.84M NGN',
    rail: 'Local rail',
    fx: '1543',
    fee: '$3.50',
    eta: 'Tomorrow',
    tone: 'mist',
    portrait: false,
    msa: 'MSA 056',
    pinX: 51, pinY: 38,
  },
];

export const ROSTER_COMPLIANT = 12;
export const ROSTER_PENDING = 3;
export const ROSTER_REJECTED = 1;

export const PROJECTS = [
  {
    id: 'atlas-ios',
    title: 'Atlas iOS rebuild',
    client: 'Atlas Health',
    contractorIds: ['priya', 'koen', 'maya'],
    currentCost: 48200,
    estimatedCost: 86000,
    progress: 0.56,
    nextMilestone: { label: 'Beta candidate · build 0.9', due: 'May 2', daysOut: 8 },
  },
  {
    id: 'lighthouse-brand',
    title: 'Lighthouse brand system',
    client: 'Lighthouse Capital',
    contractorIds: ['nathaniel', 'aoife', 'hallie'],
    currentCost: 22400,
    estimatedCost: 32000,
    progress: 0.70,
    nextMilestone: { label: 'Identity round 2 review', due: 'Apr 29', daysOut: 5 },
  },
  {
    id: 'cedar-content',
    title: 'Cedar editorial Q2',
    client: 'Cedar Books',
    contractorIds: ['hallie', 'tomi'],
    currentCost: 9180,
    estimatedCost: 18500,
    progress: 0.50,
    nextMilestone: { label: '12 articles delivery', due: 'May 16', daysOut: 22 },
  },
  {
    id: 'helix-research',
    title: 'Helix user research',
    client: 'Helix Bio',
    contractorIds: ['amaru', 'carlos'],
    currentCost: 14800,
    estimatedCost: 21000,
    progress: 0.71,
    nextMilestone: { label: 'Synthesis readout', due: 'Apr 27', daysOut: 3 },
  },
];
